# Generated by Django 4.0.3 on 2022-03-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categories_post',
            field=models.ManyToManyField(through='newspage.Postcategory', to='newspage.category'),
        ),
    ]
